version: '3.8'

services:
  db:
    image: postgres:16
    container_name: autograder_db
    environment:
      POSTGRES_DB: autograder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: autograder_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: autograder_minio
    ports:
      - "9012:9000"
      - "9013:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

#   celery:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: autograder_celery
#     command: celery -A autograder worker -l info
#     volumes:
#       - ./backend:/app
#       - /var/run/docker.sock:/var/run/docker.sock
#     depends_on:
#       - db
#       - redis
#     environment:
#       - POSTGRES_DB=autograder
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_HOST=db
#       - REDIS_URL=redis://redis:6379/1
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - DEBUG=1

volumes:
  postgres_data:
  redis_data:
  minio_data:
