# Generated by Django 4.2.7 on 2026-06-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0016_submissionattempt_response_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradebookentry",
            name="total_time_spent",
            field=models.IntegerField(default=0),
        ),
    ]
