# Generated by Django 4.2.7 on 2026-07-21 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_add_duration_minutes_to_contentitem'),
        ('submissions', '0017_add_total_time_spent_to_gradebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterGradingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_ids', models.JSONField(default=list)),
                ('total_batches', models.IntegerField(default=0)),
                ('completed_batches', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('analyzed', models.IntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log_output', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_grading_tasks', to='assignments.assignment')),
            ],
            options={
                'db_table': 'cluster_grading_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
