# Generated by Django 4.2.7 on 2026-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0008_assignmentquestion_umap_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
