# Generated by Django 4.2.7 on 2026-06-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0009_add_start_time_to_contentitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="duration_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
