const IDENTIFIER_REGEX = /^[A-Za-z_][A-Za-z0-9_]*$/;

const sanitizeIdentifier = (value, fallback) => {
    const raw = String(value || "").trim();
    if (!raw) return fallback;

    const normalized = raw
        .replace(/[^A-Za-z0-9_]/g, "_")
        .replace(/^[^A-Za-z_]+/, "");

    if (IDENTIFIER_REGEX.test(normalized)) return normalized;
    return fallback;
};

const escapeRegExp = (value) => String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const buildIndexedParams = (count) =>
    Array.from({ length: Math.max(0, count) }, (_, index) => `arg${index + 1}`);

const getConfigParamNames = (config) => {
    if (!config || typeof config !== "object") return [];

    const directNames = config.parameter_names || config.param_names;
    if (Array.isArray(directNames) && directNames.length) {
        return directNames.map((name, index) => sanitizeIdentifier(name, `arg${index + 1}`));
    }

    if (Array.isArray(config.parameters) && config.parameters.length) {
        return config.parameters.map((param, index) => {
            const rawName = typeof param === "string" ? param : param?.name;
            return sanitizeIdentifier(rawName, `arg${index + 1}`);
        });
    }

    if (Array.isArray(config.input_types) && config.input_types.length) {
        return buildIndexedParams(config.input_types.length);
    }

    return [];
};

const parseJsonIfPossible = (raw) => {
    if (typeof raw !== "string") return raw;
    const trimmed = raw.trim();
    if (!trimmed) return null;
    try {
        return JSON.parse(trimmed);
    } catch {
        return null;
    }
};

const inferParamNamesFromInputValue = (inputValue, configParamCount = 0) => {
    if (inputValue === null || inputValue === undefined) return [];

    if (Array.isArray(inputValue)) {
        if (!inputValue.length) return [];

        const hasNestedValues = inputValue.some((item) => Array.isArray(item) || (item && typeof item === "object"));
        if (hasNestedValues) return buildIndexedParams(inputValue.length);

        if (configParamCount > 1) return buildIndexedParams(configParamCount);
        return ["arg1"];
    }

    if (typeof inputValue === "object") {
        const keys = Object.keys(inputValue);
        if (!keys.length) return [];
        return keys.map((key, index) => sanitizeIdentifier(key, `arg${index + 1}`));
    }

    if (typeof inputValue === "string") {
        const trimmed = inputValue.trim();
        if (!trimmed) return [];

        const parsed = parseJsonIfPossible(trimmed);
        if (parsed !== null) {
            return inferParamNamesFromInputValue(parsed, configParamCount);
        }

        // Fallback: If JSON parsing fails, try to infer from space-separated tokens
        // e.g., "[3, 34, 4, 12, 5, 2] 9" → likely 2 params
        const tokens = trimmed.split(/\s+/).filter(t => t);
        if (tokens.length >= 2) {
            // Space-separated arguments
            return buildIndexedParams(tokens.length);
        }

        return ["arg1"];
    }

    return ["arg1"];
};

const getFirstNonEmptyInput = (testCases) => {
    if (!Array.isArray(testCases)) return null;

    for (const testCase of testCases) {
        if (!testCase || !Object.prototype.hasOwnProperty.call(testCase, "input")) continue;
        const inputValue = testCase.input;
        if (inputValue === null || inputValue === undefined) continue;
        if (typeof inputValue === "string" && !inputValue.trim()) continue;
        return inputValue;
    }

    return null;
};

const getFunctionName = (question) => {
    const config = question?.config || {};
    const directEntryPoint = config.entry_point || config.execution_mode?.entry_point;
    return sanitizeIdentifier(directEntryPoint, "solution");
};

const getExpectedParams = (question) => {
    const config = question?.config || {};
    const configParams = getConfigParamNames(config);
    if (configParams.length) return configParams;

    const inputValue = getFirstNonEmptyInput(question?.test_cases || []);
    if (inputValue === null) return [];

    return inferParamNamesFromInputValue(inputValue, configParams.length);
};

const isAutoGeneratedPythonStarter = (starterCode, functionName) => {
    if (!starterCode || !functionName) return false;
    const normalized = starterCode.trim();
    
    // Check for incomplete/broken starter code (just comments, no actual function def)
    const onlyComments = !normalized.includes("def ") || !normalized.includes(":");
    const isGenericComment = normalized.includes("Write your solution below") && !normalized.includes(`def ${functionName}`);
    
    // If it looks like incomplete boilerplate, treat as auto-generated (will regenerate)
    if (isGenericComment && onlyComments) return true;
    
    // Check for properly formed auto-generated style
    const fnPattern = new RegExp(`def\\s+${escapeRegExp(functionName)}\\s*\\([^)]*\\)\\s*:`);
    const isDefaultStyle = normalized.includes("Write your solution below")
        && normalized.includes(`The function '${functionName}' will be called with the test case inputs.`);

    return fnPattern.test(normalized) && /\bpass\b/.test(normalized) && isDefaultStyle;
};

const buildPythonBoilerplate = (functionName, params) => {
    const paramList = params.join(", ");
    return [
        "# Write your solution below",
        `# The function '${functionName}' will be called with the test case inputs.`,
        `def ${functionName}(${paramList}):`,
        "    pass",
        ""
    ].join("\n");
};

// C and Java are graded in PROGRAM mode only: the runner compiles the file and
// pipes each test case's input to stdin, then compares stdout. So the starter
// must be a complete, compilable program with an entry point — a bare function
// (no main) fails to link with "undefined reference to `main'".
const buildJavaBoilerplate = () => [
    "import java.util.Scanner;",
    "",
    "public class Main {",
    "    public static void main(String[] args) {",
    "        Scanner sc = new Scanner(System.in);",
    "        // Read the input, then print your answer with System.out.println(...)",
    "    }",
    "}",
    ""
].join("\n");

const buildCBoilerplate = () => [
    "#include <stdio.h>",
    "",
    "int main() {",
    "    // Read the input with scanf, then print your answer with printf",
    "    return 0;",
    "}",
    ""
].join("\n");

const getLanguageDefault = (language) => {
    switch ((language || "").toLowerCase()) {
        case "java":
        case "c":
            return "// Write your solution below\n";
        case "python":
        default:
            return "# Write your solution below\n";
    }
};

const getLanguageBoilerplate = (language, functionName, params) => {
    switch ((language || "").toLowerCase()) {
        case "java":
            return buildJavaBoilerplate();
        case "c":
            return buildCBoilerplate();
        case "python":
        default:
            return buildPythonBoilerplate(functionName, params);
    }
};

// Does a stored starter snippet plausibly belong to the selected language?
// Deliberately loose — it only needs to catch the common cross-language
// mismatch (Python starter shown for a C/Java attempt), not classify perfectly.
const starterMatchesLanguage = (starterCode, language) => {
    const code = String(starterCode || "");
    const lang = (language || "python").toLowerCase();

    const looksPython = /^\s*(def|class)\s+\w+.*:\s*$/m.test(code) || /^\s*import\s+\w+\s*$/m.test(code);
    const looksC = /#include\s*[<"]/.test(code) || /\b(int|void)\s+main\s*\(/.test(code);
    const looksJava = /\b(public\s+)?class\s+\w+/.test(code) && /\{/.test(code);

    if (lang === "c") return looksC;
    if (lang === "java") return looksJava;
    if (lang === "python") return looksPython || !(looksC || looksJava);
    return true;
};

export const getWorkspaceStarterCode = (question, language = "python") => {
    const starterCode = typeof question?.starter_code === "string" ? question.starter_code : "";
    const hasStarterCode = Boolean(starterCode.trim());
    const functionName = getFunctionName(question);
    
    // Get entry point from config, if present
    const configEntryPoint = question?.config?.entry_point || question?.config?.execution_mode?.entry_point;
    const hasExplicitEntryPoint = Boolean(configEntryPoint);

    // Always generate boilerplate if we have a valid function name (even if entry_point is missing, we use "solution" as fallback)
    // This ensures starter code is generated for questions where entry_point wasn't set or defaults to "solution"
    const expectedParams = getExpectedParams(question);
    const generatedCode = getLanguageBoilerplate(language, functionName, expectedParams);

    // If no starter code provided, return generated boilerplate
    if (!hasStarterCode) return generatedCode;

    // Stored starter_code is authored for ONE language (nearly always Python).
    // Handing a Python `def ...:` to a student who picked C/Java produces code
    // that cannot compile, so fall back to this language's own boilerplate
    // unless the stored snippet actually looks like the selected language.
    if (!starterMatchesLanguage(starterCode, language)) return generatedCode;

    // If we have starter code and it's auto-generated, refresh it with current params
    if (isAutoGeneratedPythonStarter(starterCode, functionName)) return generatedCode;

    // If we have explicit custom starter code, use it as-is
    return starterCode;
};

