# Generated by Django 4.2.7 on 2026-07-22 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('solved', 'Solved'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('source_code', models.TextField(blank=True)),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_total', models.IntegerField(default=0)),
                ('time_taken_sec', models.FloatField(default=0.0)),
                ('run_attempts', models.IntegerField(default=1)),
                ('rating_before', models.FloatField(default=0.0)),
                ('rating_after', models.FloatField(default=0.0)),
                ('rating_delta', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adaptive_attempts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='python', max_length=20)),
                ('entry_point', models.CharField(blank=True, default='solution', max_length=120)),
                ('starter_code', models.TextField(blank=True)),
                ('reference_solution', models.TextField(blank=True)),
                ('test_cases', models.JSONField(default=list)),
                ('elo_rating', models.FloatField(default=1500.0)),
                ('ref_time_sec', models.FloatField(default=180.0)),
                ('source', models.CharField(blank=True, default='import', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adaptive_questions',
                'ordering': ['elo_rating'],
            },
        ),
        migrations.CreateModel(
            name='MarsRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0.0)),
                ('velocity', models.FloatField(default=0.0)),
                ('n', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('peak_rating', models.FloatField(default=0.0)),
                ('rolling_updates', models.JSONField(blank=True, default=list)),
                ('topic_correct', models.JSONField(blank=True, default=dict)),
                ('topic_total', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mars_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mars_ratings',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=20)),
                ('rating_start', models.FloatField(default=0.0)),
                ('rating_end', models.FloatField(blank=True, null=True)),
                ('questions_served', models.IntegerField(default=0)),
                ('questions_solved', models.IntegerField(default=0)),
                ('questions_skipped', models.IntegerField(default=0)),
                ('current_served_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='adaptive.adaptivequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adaptive_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adaptivequestion',
            index=models.Index(fields=['elo_rating'], name='adaptive_qu_elo_rat_5a4d66_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivequestion',
            index=models.Index(fields=['is_active'], name='adaptive_qu_is_acti_0ea6f7_idx'),
        ),
        migrations.AddField(
            model_name='adaptiveattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='adaptive.adaptivequestion'),
        ),
        migrations.AddField(
            model_name='adaptiveattempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='adaptive.adaptivesession'),
        ),
        migrations.AddField(
            model_name='adaptiveattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
