# Generated by Django 4.2.7 on 2026-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptivesession',
            name='language',
            field=models.CharField(default='python', max_length=20),
        ),
    ]
